<a href="https://colab.research.google.com/github/PadmarajBhat/Deep-Learning-Introduction/blob/master/DeepLearning.ai/TensorFlow%20In%20Practice/Intro%20to%20TensorFlow/FirstNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here, when we say tensorflow import it includes all breadth of tensorflow library. And hence second line is redundant. It is added just to reduce the length of the single line of code (ease of coding)

We can also have ```from tensorflow.keras import layers``` for further simplify the code

In [0]:
import tensorflow as tf
from tensorflow import keras

Here, 1 layer NN where 1 side is input and other is output.

Input shape is 1d array hence input_shape is [1]
output shape is also 1d and hence first parameter is "1"

In [2]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=[1])
])
model.compile(optimizer='sgd',loss='mean_squared_error')

W0808 00:46:47.891603 140382160312192 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Let us build the data to be used for training the model

In [0]:
import numpy as np

xs = np.array([1,2,3,4,5,6,7,8,9], dtype=np.int)
ys = np.array([2,3,4,5,6,7,8,9,10], dtype=np.int)


Let us train the model

In [4]:
model.fit(xs,ys,epochs=100)

Epoch 1/100
9/9 [==============================] - 1s 58ms/sample - loss: 91.7235
Epoch 2/100
9/9 [==============================] - 0s 601us/sample - loss: 11.3851
Epoch 3/100
9/9 [==============================] - 0s 653us/sample - loss: 1.4992
Epoch 4/100
9/9 [==============================] - 0s 194us/sample - loss: 0.2820
Epoch 5/100
9/9 [==============================] - 0s 712us/sample - loss: 0.1315
Epoch 6/100
9/9 [==============================] - 0s 202us/sample - loss: 0.1121
Epoch 7/100
9/9 [==============================] - 0s 669us/sample - loss: 0.1090
Epoch 8/100
9/9 [==============================] - 0s 213us/sample - loss: 0.1078
Epoch 9/100
9/9 [==============================] - 0s 250us/sample - loss: 0.1069
Epoch 10/100
9/9 [==============================] - 0s 249us/sample - loss: 0.1060
Epoch 11/100
9/9 [==============================] - 0s 280us/sample - loss: 0.1051
Epoch 12/100
9/9 [==============================] - 0s 184us/sample - loss: 0.1043
Epoch 13/100

Let us see how good the model is. Predict for a unseen data.

In [5]:
model.predict([11])

array([[12.365026]], dtype=float32)

Like the one of the 6 methods to reduce overfitting, let us see if complex model solve or create problem.

In [6]:
model = keras.Sequential([
    keras.layers.Dense(5,input_shape=[1])
    ,keras.layers.Dropout(0.5)
    ,keras.layers.Dense(4)
    ,keras.layers.Dropout(0.5)
    ,keras.layers.Dense(3)
    ,keras.layers.Dropout(0.5)
    ,keras.layers.Dense(2)
    ,keras.layers.Dropout(0.5)
    ,keras.layers.Dense(1)
])
model.compile(optimizer='sgd',loss='mean_squared_error')
model.fit(xs,ys,epochs=100)
model.predict([11])

Epoch 1/100
9/9 [==============================] - 0s 21ms/sample - loss: 53.0682
Epoch 2/100
9/9 [==============================] - 0s 702us/sample - loss: 38.2618
Epoch 3/100
9/9 [==============================] - 0s 914us/sample - loss: 55.8430
Epoch 4/100
9/9 [==============================] - 0s 220us/sample - loss: 47.9736
Epoch 5/100
9/9 [==============================] - 0s 226us/sample - loss: 37.4918
Epoch 6/100
9/9 [==============================] - 0s 221us/sample - loss: 33.4557
Epoch 7/100
9/9 [==============================] - 0s 290us/sample - loss: 32.3582
Epoch 8/100
9/9 [==============================] - 0s 319us/sample - loss: 28.0244
Epoch 9/100
9/9 [==============================] - 0s 611us/sample - loss: 52.9649
Epoch 10/100
9/9 [==============================] - 0s 283us/sample - loss: 35.0170
Epoch 11/100
9/9 [==============================] - 0s 372us/sample - loss: 46.0137
Epoch 12/100
9/9 [==============================] - 0s 593us/sample - loss: 22.9514
Ep

array([[nan]], dtype=float32)

Let us increase the training samples and see if the same above model works better

In [7]:
xs = np.array(list(range(0,1000)), dtype=np.int)
ys = np.array(list(range(1,1001)), dtype=np.int)

model.fit(xs,ys,epochs=100)
model.predict([11,200])

Epoch 1/100
1000/1000 [==============================] - 0s 73us/sample - loss: nan
Epoch 2/100
1000/1000 [==============================] - 0s 45us/sample - loss: nan
Epoch 3/100
1000/1000 [==============================] - 0s 42us/sample - loss: nan
Epoch 4/100
1000/1000 [==============================] - 0s 43us/sample - loss: nan
Epoch 5/100
1000/1000 [==============================] - 0s 42us/sample - loss: nan
Epoch 6/100
1000/1000 [==============================] - 0s 43us/sample - loss: nan
Epoch 7/100
1000/1000 [==============================] - 0s 44us/sample - loss: nan
Epoch 8/100
1000/1000 [==============================] - 0s 46us/sample - loss: nan
Epoch 9/100
1000/1000 [==============================] - 0s 43us/sample - loss: nan
Epoch 10/100
1000/1000 [==============================] - 0s 43us/sample - loss: nan
Epoch 11/100
1000/1000 [==============================] - 0s 43us/sample - loss: nan
Epoch 12/100
1000/1000 [==============================] - 0s 45us/sample -

array([[nan],
       [nan]], dtype=float32)

### Does increasing the training samples help the right model ?

In [13]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=[1])
])
model.compile(optimizer='sgd',loss='mean_squared_error')
xs = np.array(list(range(0,100)), dtype=np.int)
ys = np.array(list(range(1,101)), dtype=np.int)
model.fit(xs,ys,epochs=50)
model.predict([25])

Epoch 1/50
100/100 [==============================] - 0s 2ms/sample - loss: 90079894801.2643
Epoch 2/50
100/100 [==============================] - 0s 115us/sample - loss: 19780750044894731956125696.0000
Epoch 3/50
100/100 [==============================] - 0s 97us/sample - loss: inf                          
Epoch 4/50
100/100 [==============================] - 0s 103us/sample - loss: inf
Epoch 5/50
100/100 [==============================] - 0s 105us/sample - loss: inf
Epoch 6/50
100/100 [==============================] - 0s 116us/sample - loss: nan
Epoch 7/50
100/100 [==============================] - 0s 106us/sample - loss: nan
Epoch 8/50
100/100 [==============================] - 0s 78us/sample - loss: nan
Epoch 9/50
100/100 [==============================] - 0s 95us/sample - loss: nan
Epoch 10/50
100/100 [==============================] - 0s 98us/sample - loss: nan
Epoch 11/50
100/100 [==============================] - 0s 130us/sample - loss: nan
Epoch 12/50
100/100 [==============

array([[nan]], dtype=float32)