<a href="https://colab.research.google.com/github/PadmarajBhat/Deep-Learning-Introduction/blob/master/FirstNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here, when we say tensorflow import it includes all breadth of tensorflow library. And hence second line is redundant. It is added just to reduce the length of the single line of code (ease of coding)

We can also have ```from tensorflow.keras import layers``` for further simplify the code

In [0]:
import tensorflow as tf
from tensorflow import keras

Here, 1 layer NN where 1 side is input and other is output.

Input shape is 1d array hence input_shape is [1]
output shape is also 1d and hence first parameter is "1"

In [2]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=[1])
])
model.compile(optimizer='sgd',loss='mean_squared_error')

W0808 00:25:47.313212 140218321680256 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Let us build the data to be used for training the model

In [0]:
import numpy as np

xs = np.array([1,2,3,4,5,6,7,8,9], dtype=np.int)
ys = np.array([2,3,4,5,6,7,8,9,10], dtype=np.int)


Let us train the model

In [4]:
model.fit(xs,ys,epochs=100)

Epoch 1/100
9/9 [==============================] - 0s 52ms/sample - loss: 32.5549
Epoch 2/100
9/9 [==============================] - 0s 257us/sample - loss: 4.1357
Epoch 3/100
9/9 [==============================] - 0s 362us/sample - loss: 0.6378
Epoch 4/100
9/9 [==============================] - 0s 197us/sample - loss: 0.2064
Epoch 5/100
9/9 [==============================] - 0s 335us/sample - loss: 0.1523
Epoch 6/100
9/9 [==============================] - 0s 158us/sample - loss: 0.1446
Epoch 7/100
9/9 [==============================] - 0s 145us/sample - loss: 0.1426
Epoch 8/100
9/9 [==============================] - 0s 127us/sample - loss: 0.1413
Epoch 9/100
9/9 [==============================] - 0s 127us/sample - loss: 0.1402
Epoch 10/100
9/9 [==============================] - 0s 115us/sample - loss: 0.1390
Epoch 11/100
9/9 [==============================] - 0s 104us/sample - loss: 0.1379
Epoch 12/100
9/9 [==============================] - 0s 159us/sample - loss: 0.1367
Epoch 13/100


Let us see how good the model is. Predict for a unseen data.

In [5]:
model.predict([11])

array([[12.417998]], dtype=float32)

Like the one of the 6 methods to reduce overfitting, let us see if complex model solve or create problem.

In [12]:
model = keras.Sequential([
    keras.layers.Dense(5,input_shape=[1])
    ,keras.layers.Dropout(0.5)
    ,keras.layers.Dense(4)
    ,keras.layers.Dropout(0.5)
    ,keras.layers.Dense(3)
    ,keras.layers.Dropout(0.5)
    ,keras.layers.Dense(2)
    ,keras.layers.Dropout(0.5)
    ,keras.layers.Dense(1)
])
model.compile(optimizer='sgd',loss='mean_squared_error')
model.fit(xs,ys,epochs=100)
model.predict([11])

Epoch 1/100
9/9 [==============================] - 0s 26ms/sample - loss: 1043.0002
Epoch 2/100
9/9 [==============================] - 0s 525us/sample - loss: 7367768898797568.0000
Epoch 3/100
9/9 [==============================] - 0s 351us/sample - loss: nan
Epoch 4/100
9/9 [==============================] - 0s 275us/sample - loss: nan
Epoch 5/100
9/9 [==============================] - 0s 325us/sample - loss: nan
Epoch 6/100
9/9 [==============================] - 0s 314us/sample - loss: nan
Epoch 7/100
9/9 [==============================] - 0s 476us/sample - loss: nan
Epoch 8/100
9/9 [==============================] - 0s 267us/sample - loss: nan
Epoch 9/100
9/9 [==============================] - 0s 479us/sample - loss: nan
Epoch 10/100
9/9 [==============================] - 0s 390us/sample - loss: nan
Epoch 11/100
9/9 [==============================] - 0s 489us/sample - loss: nan
Epoch 12/100
9/9 [==============================] - 0s 279us/sample - loss: nan
Epoch 13/100
9/9 [========

array([[nan]], dtype=float32)

Let us increase the training samples and see if the same above model works better

In [18]:
xs = np.array(list(range(0,1000)), dtype=np.int)
ys = np.array(list(range(1,1001)), dtype=np.int)

model.fit(xs,ys,epochs=100)
model.predict([11,200])

Epoch 1/100
1000/1000 [==============================] - 0s 47us/sample - loss: nan
Epoch 2/100
1000/1000 [==============================] - 0s 43us/sample - loss: nan
Epoch 3/100
1000/1000 [==============================] - 0s 42us/sample - loss: nan
Epoch 4/100
1000/1000 [==============================] - 0s 39us/sample - loss: nan
Epoch 5/100
1000/1000 [==============================] - 0s 43us/sample - loss: nan
Epoch 6/100
1000/1000 [==============================] - 0s 40us/sample - loss: nan
Epoch 7/100
1000/1000 [==============================] - 0s 43us/sample - loss: nan
Epoch 8/100
1000/1000 [==============================] - 0s 47us/sample - loss: nan
Epoch 9/100
1000/1000 [==============================] - 0s 45us/sample - loss: nan
Epoch 10/100
1000/1000 [==============================] - 0s 44us/sample - loss: nan
Epoch 11/100
1000/1000 [==============================] - 0s 39us/sample - loss: nan
Epoch 12/100
1000/1000 [==============================] - 0s 41us/sample -

array([[nan],
       [nan]], dtype=float32)